name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Release - ${{ matrix.platform.name }}
    strategy:
      fail-fast: true
      matrix:
        # Supported targets
        # https://github.com/cross-rs/cross#supported-targets
        platform:
          - name: linux-x64
            runs-on: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - name: windows-x64
            runs-on: ubuntu-latest
            target: x86_64-pc-windows-gnu

          - name: macos-x64
            runs-on: ubuntu-latest
            target: x86_64-apple-darwin

          - name: macos-arm64
            runs-on: ubuntu-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Zip
        shell: pwsh
        run: |
          Set-Location "target/${{ matrix.platform.target }}/release"
          $files = Get-ChildItem "*steam_api*", "SAM*"
          $files = $files | Where-Object { $_.Name -notlike "*.d" -and $_.Name -notlike "*.pdb" }
          Compress-Archive -Path $files -DestinationPath "../../../SAM-${{ matrix.platform.name }}.zip"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SAM-${{ matrix.platform.name }}
          path: SAM-${{ matrix.platform.name }}.zip

  release:
    name: Release
    needs: build
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Cargo.toml Version
        id: get_version
        run: |
          version=$(grep '^version' Cargo.toml | head -n 1 | sed 's/version = "\(.*\)"/\1/')
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: "${{ env.VERSION }}"
          files: |
            LICENSE
            README.md
            **/*.zip
